/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    copy: typeof import('./components/ToyPad.old copy.vue')['default']
    DeleteToy: typeof import('./components/DeleteToy.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ToyPad: typeof import('./components/ToyPad.vue')['default']
    'ToyPad.old': typeof import('./components/ToyPad.old.vue')['default']
    ToyTag: typeof import('./components/ToyTag.vue')['default']
  }
}
